version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: pdepapel-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pdepapel_dev
    ports:
      - "3306:3306"
    volumes:
      - pdepapel-mysql-data:/var/lib/mysql
    restart: unless-stopped

volumes:
  pdepapel-mysql-data:
